name: Build Executables

on:
  push:
    branches: [main] # Adjust this if you want to trigger on different branches

jobs:
  # build-macos:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: "3.10" # Adjust this to your preferred Python version
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt  # Make sure you have this file in your repository
  #     - name: Create macOS Executable
  #       uses: Martin005/pyinstaller-action@v1.2.0
  #       with:
  #         spec: "p2p_volume_monitor.py"
  #         options: --onefile --name "P2P Volume Monitor - macOS"
  #         upload_exe_with_name: p2p-volume-monitor-macos

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10" # Adjust this to your preferred Python version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Make sure you have this file in your repository
      - name: Create Windows Executable
        uses: Martin005/pyinstaller-action@v1.2.0
        with:
          spec: "p2p_volume_monitor.py"
          options: --onefile --name "P2P Volume Monitor - Windows"
          upload_exe_with_name: p2p-volume-monitor-windows
